version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - dogsled
    - errcheck
    - errorlint
    - gocritic
    - gocyclo
    - goheader
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nestif
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 2
      min-occurrences: 2
    gosec:
      excludes:
        - G101
        - G115
    misspell:
      locale: US
      ignore-rules:
        - cancelled
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - predeclared
        path: internal/xatomic/type.go
      - linters:
          - unparam
          - unused
        path: _test\.go
      - path: (.+)\.go$
        text: has been deprecated since Go 1.16
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/ydb-platform/terraform-provider-ydb
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
