services:
  ydb:
    image: ydbplatform/local-ydb:edge
    pull_policy: always
    hostname: localhost
    ports:
      - "${YDB_GRPCS_PORT:-2135}:${YDB_GRPCS_PORT:-2135}"
      - "${YDB_GRPC_PORT:-2136}:${YDB_GRPC_PORT:-2136}"
      - "${YDB_MON_PORT:-8765}:${YDB_MON_PORT:-8765}"
    environment:
      GRPC_TLS_PORT: "${YDB_GRPCS_PORT:-2135}"
      GRPC_PORT: "${YDB_GRPC_PORT:-2136}"
      MON_PORT: "${YDB_MON_PORT:-8765}"
      YDB_FEATURE_FLAGS: "\
        enable_replace_if_exists_for_external_entities,\
        enable_external_data_sources,\
        enable_schema_secrets,\
        enable_resource_pools"
