name: lint
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  golangci:
    name: golangci-lint
    concurrency:
      group: lint-golangci-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
  autoformatter:
    name: autoformat check
    concurrency:
      group: lint-autoformat-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install utilities
        run: |
          go install mvdan.cc/gofumpt@v0.3.1
          go install github.com/rinchsan/gosimports/cmd/gosimports@v0.1.5

      - name: format all files with auto-formatter
        run: bash ./.github/scripts/format-all-go-code.sh "$PWD"

      - name: Check repository diff
        run: bash ./.github/scripts/check-work-copy-equals-to-committed.sh "auto-format broken"

